### PR TITLE
feat: build for arm64 too

### PR DESCRIPTION
**Pull request by dimaqq**

### CODE REVIEW

**Comment by dimaqq** [comment]
Blocked by charmcraft failing to use specified node.js version.

**Comment by simskij** [comment]
is this something you are still looking to complete? if not, we should close the pr.

**Comment by dimaqq** [comment]
Let me see if rockcraft has gotten better.

**Comment by lucabello** [comment]
@dimaqq Any news?

**Comment by lucabello** [comment]
Actually, addressing this as part of #63, and closing this PR :)

**Pull request closed without merging**
